[project]
name = "Combfold"
version = "0.1.0"
description = "Add a short description here"
authors = ["B Shor et al"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[tasks]
make = "bash install.sh"

[dependencies]
libboost = ">=1.84.0,<1.85"
make = ">=4.3,<5"
cxx-compiler = ">=1.7.0,<1.8"
libboost-devel = ">=1.84.0,<1.85"
boost = ">=1.84.0,<1.85"
colabfold = ">=1.5.5,<1.6"
numpy = ">=1.26.4,<1.27"
biopython = ">=1.82,<2"
scipy = ">=1.13.0,<1.14"
