[project]
name = "Combfold"
version = "0.1.0"
description = "Add a short description here"
authors = ["B Shor et al"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[tasks]
make = "bash install.sh"

[dependencies]
#libboost = ">=1.84.0,<1.85"
make = ">=4.3,<5"
cxx-compiler = ">=1.7.0,<1.8"
boost = ">=1.84.0,<1.85"
biopython = "*"
scipy = "*"
numpy = "*"
colabfold = ">=1.5.5,<1.6"
jax = ">=0.4.25,<0.5"
pip = ">=24.0,<25"
libboost = ">=1.84.0,<1.85"
libboost-devel = ">=1.84.0,<1.85"
#libboost-devel = ">=1.84.0,<1.85"
#boost = ">=1.84.0,<1.85"
#jaxlib = ">=0.4.23,<0.5"
#cuda-nvcc = ">=12.4.131,<12.5"
#rocm-opencl = ">=6.0.2,<6.1"
